[package]
name = "dynamic-staking-auto-compound-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.dynamic-staking-auto-compound]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.5"
